FROM node:alpine
WORKDIR /client2
COPY package.json .
RUN npm i
COPY tsconfig.json tsconfig.json
COPY webpack.config.js webpack.config.js
COPY public public
COPY src src
RUN npm run build
CMD npm start