version: "3.9"
services:
  deck:
    build: deck
  word:
    build: word
    environment:
      - WORD_FILE=words.txt
    ports:
      - "5000:5001"
  little:
    build: little
    environment:
      - DECK_HOST=deck
      - DECK_PORT=5000
    ports:
      - "80:3000"