version: "3.9"
services:
  deck:
    build: deck
    ports:
      - "5000:5000"
  word:
    build: word
    environment:
      - WORD_FILE=words.txt
    ports:
      - "5001:5001"
  web:
    build: web_serve
    ports:
      - "80:3000"
