version: "3.9"
services:
  client:
    build: client
    ports:
      - 3000
  home:
    build: homepage
    ports:
      - 3001
  deck:
    build: deck
    ports:
      - 5001
  word:
    build: word
    environment:
      - WORD_FILE=words.txt
    ports:
      - 5002
  web:
    build: web
    environment:
      - client-host=client
      - client-port=3000
      - deck-host=deck
      - deck-port=5001
      - word-host=word
      - word-port=5002
      - home-host=home
      - home-port=3001
    ports:
      - "80:8080"
