version: "3.9"
services:
  client:
    image: hannahellis4242/tarot_client:latest
    ports:
      - 3000
  deck:
    image: hannahellis4242/tarot_deck:latest
    ports:
      - 5001
  word:
    image: hannahellis4242/tarot_word:latest
    environment:
      - WORD_FILE=words.txt
    ports:
      - 5002
  web:
    image: hannahellis4242/tarot_web:latest
    environment:
      - client-host=client
      - client-port=3000
      - deck-host=deck
      - deck-port=5001
      - word-host=word
      - word-port=5002
    ports:
      - "80:8080"
