name: Docker Image CI - client2

on:
  push:
    paths:
      - "client2/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push client2 Image
        run: |
          docker build ./client2 --file client2/dockerfile --tag ghcr.io/hannahellis4242/tarot/client2:latest
          docker push ghcr.io/hannahellis4242/tarot/client2:latest
